// generated by CommonLibrary.cmake, do not edit.

#include <servus/version.h>

namespace servus
{

int Version::getMajor()
{
    return SERVUS_VERSION_MAJOR;
}

int Version::getMinor()
{
    return SERVUS_VERSION_MINOR;
}

int Version::getPatch()
{
    return SERVUS_VERSION_PATCH;
}

int Version::getABI()
{
    return SERVUS_VERSION_ABI;
}

std::string Version::getString()
{
    return SERVUS_VERSION_STRING;
}

unsigned long long Version::getRevision()
{
    return SERVUS_VERSION_REVISION;
}

std::string Version::getRevString()
{
    return SERVUS_REV_STRING;
}

}
